### ISSUE TITLE
Contact info flipping between subjects

### ISSUE THREAD

**Issue by vladimir-mencl-eresearch** [ausaccessfed/federationregistry#201]
Hi,

I've run into an obscure issue.

When two separate identities (Subject instances) logging into FR have the same email address, they get to share the Contact record.  This happened to me with my institutional and my VHO login.

When later one of them gets the email address changed, on next login with this identity, the Contact info gets _updated_ - instead of creating a new Contact record.

When later logging back in with the original identity (where the email address remained unchanged), the Contact record gets updated again, reverting back to the original email address.

The updates propagate to the generated metadata and may generate spurious metadata update messages, flipping back and forth.

I don't know whether there can be something done about this.  This is a very special case of me shifting my VHO identity to a different email address, but temporarily still keeping my institutional account.

I have fixed this for myself by manually creating a new Contact record and updating my Subject to point to the separate Contact record.

For the general case, I see the rationale for updating the existing Contact record - it just has undesired consequences if the Contact record is shared between several subjects.

Bradley, Shaun, any thoughts on this?

Cheers,
Vlad

**Comment by vladimir-mencl-eresearch** [comment]
FYI, this is the code I used to update the Subject.contact reference:

````
import aaf.fr.foundation.*
import aaf.fr.identity.*
  
def emailAddress = "new@email.address.com"
def commit = false
  
Contact c = Contact.findByEmail(emailAddress)
Subject s = Subject.findByEmail(emailAddress)

println "Located contact: " + c
println "Located subject: " + s
println "Current contact stored with subject: " + s.contact

if (commit) {
  println "Updating contact"
  s.contact = c
  s.save()
  println s.contact
  println "Current contact stored with subject: " + s.contact
}
````

**Comment by bradleybeddoes** [comment]
@vladimir-mencl-eresearch certainly an edge case, updating change of email address (due to change of name etc) was certainly the intent here.

I am going to leave this one open for now, we'll consider ways to address it as we start to consider next generation of FR/whatever-app code.

cc @smangelsdorf
