### ISSUE TITLE
Scope field doesn’t accept “-“

### ISSUE THREAD

**Issue by trsau** [ausaccessfed/federationregistry#204]
The folks from Singapore want to add a scope of “a-star.edu.sg” but FR does not currently allow the "-" or dash character in the scope field. Is there a restricted character set defined that FR is working too?

**Comment by bradleybeddoes** [comment]
This is restricted on creation, however it can be edited successfully post creation:

https://www.dropbox.com/s/ef0xm1pkz5mn3s1/Screenshot%202015-08-24%2014.18.24.png

Will leave this issue open for future correct in `views/templates/identityprovider/_create.gsp` which is limiting characters based on Javascript.
