### ISSUE TITLE
Contacts disappearing with FR 2.9

### ISSUE THREAD

**Issue by vladimir-mencl-eresearch** [ausaccessfed/federationregistry#248]
Hi @bradleybeddoes ,

When testing #247, I got changes from #243 merged in - and was surprised to see all contacts dropped from my metadata (in my isolated DEV environment).

Turned out, even though `app/plugins/base/grails-app/domain/aaf/fr/foundation/Contact.groovy` sets default value for active to `true`, all existing Contacts defaulted to false.

After some digging (and inspired by https://stackoverflow.com/questions/16505968/how-to-set-default-value-for-domain-class-values-in-grails-2-2/17623185), I got this sorted with:

```
@@ -43,6 +43,7 @@ class Contact {
        static mapping = {
                autoImport false
                sort "surname"
+               active defaultValue: true
        }

        public String toString() { "contact:[id:$id, givenName: $givenName, surname: $surname, email: $email]" }
```

I also found it surprising that the UI left no way to:
1. find and re-active inactive contacts
2. actually remove association of inactive contacts with an entity

I have a local change that addresses 1 by listing all Contacts regardless of their active status but adds Active as another column to the listing.

And I'm thinking 2 would be best addressed by also listing inactive contacts on the IdP/SP details page - so that they can be removed from the listing (to make sure they don't jump in when a contact gets marked active again).

I wanted to check with you on these before I send a PR - what are your thoughts on these?
(The static mapping and the proposed UI changes) ?

Thanks a lot in advance for getting back to me.

Cheers,
Vlad

**Comment by bradleybeddoes** [comment]
Vlad - you're right, this is a caveat. I addressed it in our upgrade process by running a SQL query to set all contacts active post upgrade. Your proposal of `active defaultValue: true` is much cleaner, happy to merge a PR on that specific aspect.

On the other points you're correct, none of that was done. AAF support was involved in the decision making on this, all they needed is what was delivered i.e. active toggle flag.

The rest of the work we're not undertaking. We're trying to do as little as possible now with FR and invest effort towards new infrastructure and tooling going forward. Keeping FR as stable as possible is our primary goal with this project now, very much a maintenance only approach.

Of course you're still welcome to send FR functionality PR if you feel something is necessary on the Tuakiri side but reviewing them will be well down on my list of of activities. Knowlege that a PR had been proven in production over an extended period without any breakage is likely to help get said PR merged at this point.
