### ISSUE TITLE
FR not exposing Organisation.Description

### ISSUE THREAD

**Issue by vladimir-mencl-eresearch** [ausaccessfed/federationregistry#250]
Organisation has a
* name (machine readable)
* displayName (human readable)
* description (a short blurb)

But for an Organisation, the description is not exposed in the UI.  For an IdP and SP, it is, but not for an Organisation.

The downside is that organisations get synchronizes into the VHO with null description.

And when attempting to edit the Organisation in VHO (e.g., to set the scope), I have to set the description to something non-empty ... which gets discarded in the next round of FR-VHO sync.

This is only a mild pain - I usually edit each Org in VHO just once, to set the scope.

I see three options:
1. leave as-is and live with the mild pain.
2. expose org.description in the FR UI (full and proper matching of the domain model and the UI)
3. drop the requirement for non-empty Org.description in VHO (remove the pain-point)

Not having the Org.description in the UI looks like an ommision to me, but probably not worth the effort - nobody seems to have needed it so far.  @bradleybeddoes , would you have any background info on that?  Was it intentional not including it in the Org detail page?

This is probably best left as-is in FR - but @bradleybeddoes , would you welcome a PR to the VHO doing 3?

Cheers,
Vlad

**Comment by bradleybeddoes** [comment]
Just an oversight, clearly never needed.

Closing but noting requirement for next gen of tooling.
